#!/usr/bin/env bash

if [ $EUID -eq 0 ]; then
  echo "This script must not be run as root"
  exit
fi

[[ -n "$SUDO_USER" ]] && RUNUSER=$SUDO_USER || RUNUSER=$LOGNAME

if [ "$(pgrep -u "$RUNUSER" hl2_linux)" != "" ]; then
  echo TF2 Already Running!
  exit
fi

if [ "$(pgrep -u "$RUNUSER" steam)" = "" ]; then
  echo Steam not running! Starting it.
  steam >/dev/null 2>&1 &
  sleep 30
  echo Done starting Steam
fi

FILENAME="/tmp/.gl$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 6)"

cp "bin/libcathook.so" "$FILENAME"

echo "Preloading Rosnehook as $FILENAME!"
TF2_PATH=$(realpath ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/)
pushd "$TF2_PATH" || exit
LD_PRELOAD="$FILENAME" LD_LIBRARY_PATH="$TF2_PATH/bin" "$TF2_PATH/hl2_linux" -game tf >/dev/null 2>&1 &
echo "Game preloading!"
popd || exit
sleep 10
rm "$FILENAME"
